const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const promptCode=fs.readFileSync(path.join(__dirname,'../scripts/individual_prompt.js'),'utf8');
const extractCode=fs.readFileSync(path.join(__dirname,'../scripts/individual_extract.js'),'utf8');
const config={enviar:false,usarImagem:true,enviarLinksFontes:true};
const fontes=[1,2,3,4,5].map(i=>({id:'https://example.com/'+i,link:'https://example.com/'+i,titulo:'Notícia '+i,texto:'Informação da fonte. '.repeat(30),imagemUrl:'https://example.com/capa.jpg'}));
const story=f=>({id:f.id,emoji:'📊',titulo:f.titulo,resumo:'A empresa divulgou os resultados do trimestre e explicou o que mudou nos indicadores apresentados. '.repeat(2)+'\n\nO resultado deve ser entendido no contexto informado pela fonte, sem previsão de desempenho futuro.'});
const response=items=>({candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(items)}]}}]});
const extract=(items,diario=false,c=config)=>new Function('$input','$',extractCode)({first:()=>({json:response(items)})},name=>({first:()=>({json:name==='Configurar Cliente'?c:{noticias:fontes,diario}})}));
const news=extract(fontes.map(story));assert.equal(news.length,5);assert(news.every(n=>n.json.imagemUrl));
assert(news[0].json.mensagem.endsWith(fontes[0].link));
assert(!extract([story(fontes[0])],false,{...config,enviarLinksFontes:false})[0].json.mensagem.includes('https://'));
assert.equal(extract([])[0].json.semNoticias,true);
const digest=extract(fontes.map(story).reverse(),true);assert.equal(digest.length,1);assert.equal(digest[0].json.quantidadeNoticias,5);assert.equal(digest[0].json.imagemUrl,'');
assert(digest[0].json.mensagem.indexOf('*NOTÍCIA 1*')<digest[0].json.mensagem.indexOf('*NOTÍCIA 5*'));
assert.throws(()=>extract(fontes.slice(0,4).map(story),true),/TODAS/);
assert.throws(()=>extract([{...story(fontes[0]),id:'forjado'}]),/desconhecida/);
assert.throws(()=>extract([story(fontes[0]),story(fontes[0])]),/repetida/);
const long=fontes.map(f=>({...story(f),resumo:story(f).resumo.repeat(3)}));
assert(extract(long,true)[0].json.mensagem.length>3000);
const diario=new Function('$input','$',promptCode)({all:()=>[]},name=>({first:()=>({json:name==='Configurar Cliente'?config:{acao:'resumao',noticias:fontes.map(f=>({...f,registroId:f.id,resumo:f.texto}))}})}))[0].json;
assert.equal(diario.noticias.length,5);assert(diario.prompt.includes('TODAS'));
console.log('PASS notícias individuais com imagem, fontes, resumo único completo, ordem e ausência de corte em 3000.');
