const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const code=fs.readFileSync(path.join(__dirname,'../scripts/editorial_extract.js'),'utf8');
const fontes=[{link:'https://braziljournal.com/a',imagemUrl:''},{link:'https://braziljournal.com/b',imagemUrl:'https://example.com/capa.jpg'}];
const config={usarImagem:true,enviar:false};
const response=arr=>({candidates:[{finishReason:'STOP',content:{parts:[{thought:true,text:'ignorar'},{text:JSON.stringify(arr)}]}}]});
const run=(arr,f=fontes,c=config)=>new Function('$input','$',code)({first:()=>({json:response(arr.map(n=>({...n,referencias:n.referencias??[...new Set(n.link.split('|').map(s=>s.trim()))].map((url,i)=>({noticia:i+1,links:[url]}))})))})},name=>({first:()=>({json:name==='Montar Prompt'?{noticias:f}:c})}));
const story={emoji:'🚨',titulo:'RESUMÃO DO MERCADO — 2 NOTÍCIAS PARA FICAR DE OLHO',resumo:'🏦 *BANCOS DIVULGAM RESULTADOS*\nOs bancos apresentaram os resultados do trimestre, com os números disponíveis nas fontes fornecidas.\n\n✈️ *AVIAÇÃO TEM NOVOS PEDIDOS*\nA fabricante anunciou novos pedidos de aeronaves, conforme os dados divulgados na matéria.',link:fontes.map(f=>f.link).join(' | ')};
const out=run([story]);assert.equal(out.length,1);assert.equal(out[0].json.quantidadeNoticias,2);
assert(out[0].json.mensagem.startsWith('🚨 *RESUMÃO'));
assert.equal(out[0].json.imagemUrl,fontes[1].imagemUrl);
const hidden=run([story],fontes,{...config,enviarLinksFontes:false})[0].json;
assert.equal(hidden.mensagem, out[0].json.mensagem.split('\n\nNotícia 1:')[0]);
assert.equal(hidden.imagemUrl,out[0].json.imagemUrl);
assert(!/https?:\/\//.test(hidden.mensagem));
assert.equal(hidden.links.length,2);
assert.throws(()=>run([{...story,link:'https://example.com/forjado'}],fontes,{enviarLinksFontes:false}),/fontes/);
assert.equal(out[0].json.mensagem.split('RESUMÃO DO MERCADO').length-1,1);
assert(out[0].json.mensagem.endsWith(fontes.map((f,i)=>`Notícia ${i+1}: ${f.link}`).join('\n')));
assert.equal(run([story],fontes,{usarImagem:false})[0].json.imagemUrl,'');
assert.deepEqual(run([]),[]);
const cincoFontes=Array.from({length:5},(_,i)=>({link:`https://example.com/${i}`}));
const cinco={emoji:'🚨',titulo:'RESUMÃO DO MERCADO — 5 NOTÍCIAS PARA FICAR DE OLHO',resumo:cincoFontes.map((_,i)=>`📊 *ACONTECIMENTO ${i+1}*\nInformação econômica relevante conforme os dados da fonte.`).join('\n\n'),link:cincoFontes.map(f=>f.link).join(' | ')};
assert.equal(run([cinco],cincoFontes)[0].json.quantidadeNoticias,5);
assert.throws(()=>run([story,story]),/exatamente 1/);
assert.throws(()=>run([{...story,link:story.link+' | https://example.com/forjado'}]),/fontes/);
assert.throws(()=>run([{...story,resumo:story.resumo+' https://example.com'}]),/links no corpo/);
assert.throws(()=>run([{...story,resumo:story.titulo+'\n'+story.resumo}]),/abertura/);
assert.throws(()=>run([{...story,titulo:story.titulo.replace('2','3')}]),/quantidade/);
assert.throws(()=>run([{...story,resumo:'curto'}]),/insuficiente/);
const duplicate=run([{...story,link:story.link+' | '+fontes[0].link}]);assert.equal(duplicate[0].json.links.length,2);
const terceira={link:'https://braziljournal.com/c'};
const multi={...story,link:story.link+' | '+terceira.link,referencias:[{noticia:2,links:[fontes[1].link]},{noticia:1,links:[fontes[0].link,terceira.link]}]};
assert(run([multi],[...fontes,terceira])[0].json.mensagem.endsWith(`Notícia 1: ${fontes[0].link} | ${terceira.link}\nNotícia 2: ${fontes[1].link}`));
assert.throws(()=>run([{...multi,referencias:[{noticia:1,links:[fontes[0].link]},{noticia:1,links:[fontes[1].link]}]}],[...fontes,terceira]),/Numeração/);
assert.throws(()=>run([{...multi,referencias:[{noticia:1,links:[fontes[0].link]},{noticia:2,links:[fontes[1].link]}]}],[...fontes,terceira]),/associação/);
const longSources=fontes.map(f=>({...f,link:f.link+'x'.repeat(1500)}));
const maior=run([{...story,resumo:story.resumo+' Texto adicional.'.repeat(90)}])[0].json.mensagem;
assert(maior.length>1600 && maior.length<=3000);
assert(story.titulo.length+story.resumo.length<3000);
assert.throws(()=>run([{...story,link:longSources.map(f=>f.link).join(' | ')}],longSources),/3000/);
assert(run([{...story,link:longSources.map(f=>f.link).join(' | ')}],longSources,{enviarLinksFontes:false})[0].json.mensagem.length<3000);
console.log('PASS resumão único, fontes múltiplas, imagem, seleção vazia, contagem, abertura e limite incluindo URLs.');
