const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const input=process.argv[2]||'noticias_investimento_whatsapp.json';
const output=process.argv[3]||input;
const raw=JSON.parse(fs.readFileSync(input,'utf8'));const w=Array.isArray(raw)?raw[0]:raw;
const before=structuredClone(w);
const gemini=w.nodes.find(n=>n.name==='Gemini (JSON estruturado)');
const name={prepare:'Gemini · Preparar tentativa',check:'Gemini · Conferir resposta',gate:'Gemini · Concluiu?',wait:'Gemini · Aguardar e tentar novamente'};
const oldNames=new Set(w.nodes.filter(n=>n.id.startsWith('gemini-retry-')).map(n=>n.name));
w.nodes=w.nodes.filter(n=>!n.id.startsWith('gemini-retry-'));
for(const k of oldNames)delete w.connections[k];
const [x,y]=gemini.position;
const make=(id,name,type,position,parameters,typeVersion=2)=>({id:'gemini-retry-'+id,name,type:'n8n-nodes-base.'+type,typeVersion,position,parameters});
const prepare=make('prepare',name.prepare,'code',[x,y-240],{mode:'runOnceForAllItems',jsCode:fs.readFileSync(path.join(__dirname,'gemini_attempt.js'),'utf8')});
const check=make('check',name.check,'code',[x+220,y-240],{mode:'runOnceForAllItems',jsCode:fs.readFileSync(path.join(__dirname,'gemini_result.js'),'utf8')});
const gate=make('gate',name.gate,'if',[x+440,y-240],{conditions:{options:{caseSensitive:true,leftValue:'',typeValidation:'strict',version:2},conditions:[{id:'gemini-success',leftValue:'={{ $json.geminiConcluido }}',rightValue:'',operator:{type:'boolean',operation:'true',singleValue:true}}],combinator:'and'},options:{}},2.2);
const wait={...make('wait',name.wait,'wait',[x+660,y-460],{resume:'timeInterval',amount:'={{ $json.esperaSegundos }}',unit:'seconds'},1.1),webhookId:'83b72208-50fa-4f27-8779-a3991560a7bb'};
w.nodes.push(prepare,check,gate,wait,{id:'gemini-retry-guide',name:'Gemini · Como funcionam as tentativas',type:'n8n-nodes-base.stickyNote',typeVersion:1,position:[x,y-720],parameters:{width:740,height:210,content:'## Recuperação automática do Gemini\nTimeout, falha de rede, HTTP 408, 429 e 5xx: reintentos IMEDIATOS de ~10-16s entre tentativas (até 6 tentativas no total). Respeita Retry-After do servidor com teto de 60s.\nApós 6 tentativas sem sucesso a execução termina com erro claro (sem esperar minutos). Na próxima execução programada o sistema tenta novamente.\nSomente o Gemini é repetido. Os envios de WhatsApp continuam sem repetição automática.'}});
gemini.retryOnFail=false;delete gemini.maxTries;delete gemini.waitBetweenTries;
gemini.onError='continueRegularOutput';
gemini.parameters.options={...gemini.parameters.options,timeout:120000,response:{response:{responseFormat:'text',outputPropertyName:'body',fullResponse:true,neverError:true}}};
const edge=node=>({node,type:'main',index:0});
for(const [a,b]of [['Montar Prompt',name.prepare],[name.prepare,gemini.name],[gemini.name,name.check],[name.check,name.gate],[name.wait,name.prepare]])w.connections[a]={main:[[edge(b)]]};
w.connections[name.gate]={main:[[edge('Extrair Resposta da IA')],[edge(name.wait)]]};
for(const n of before.nodes)if(n.id!==gemini.id&&!n.id.startsWith('gemini-retry-'))assert.deepEqual(w.nodes.find(a=>a.id===n.id),n);
for(const [k,v]of Object.entries(before.connections))if(!['Montar Prompt',gemini.name,...oldNames].includes(k))assert.deepEqual(w.connections[k],v);
fs.writeFileSync(output,JSON.stringify(Array.isArray(raw)?[w]:w,null,2)+'\n');
console.log(JSON.stringify({retryInstalled:true,otherNodesUnchanged:true,whatsappRetries:false,transientAttempts:'6 tentativas imediatas'}));
